services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    tty: true
    command: ["bash"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent-web
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    command: ["streamlit", "run", "/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - ai-agent